# generated by datamodel-codegen:
#   filename:  ipfs-pinning-service.yaml
#   timestamp: 2023-04-04T00:52:05+00:00
from pydantic import BaseModel
from pydantic import Field


class Error(BaseModel):
    reason: str = Field(
        example="ERROR_CODE_FOR_MACHINES", description="The type of error"
    )

    details: str | None = Field(
        None,
        example="Explanation for humans with more details",
        description="Longer description of the error",
    )


class Failure(BaseModel):
    error: Error
